# Generated by Django 2.2.9 on 2022-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_lunches_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя из внешнего сервиса'),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия из внешнего сервиса'),
        ),
    ]
